use_frameworks!

platform :ios, '10.0'

target 'XJHTextInputIntercepterKit_Example' do
  pod 'XJHTextInputIntercepterKit', :path => '../'
  
  pod 'Masonry'
  pod 'ReactiveObjC', '~> 3.1.0'
  
  pod 'XJHMultiProxyKit'
  
#  pod 'XJHMultiProxyKit', :path => '../../XJHMultiProxyKit', :inhibit_warnings => false

  target 'XJHTextInputIntercepterKit_Tests' do
    inherit! :search_paths

    
  end
end
