use_frameworks!

platform :ios, '8.0'

target 'XJHTextInputIntercepterKit_Example' do
  pod 'XJHTextInputIntercepterKit', :path => '../'

  target 'XJHTextInputIntercepterKit_Tests' do
    inherit! :search_paths

    
  end
end
