use_frameworks!

platform :ios, '10.0'

target 'XJHTextInputIntercepterKit_Example' do
  pod 'XJHTextInputIntercepterKit', :path => '../'
  
  pod 'Masonry'
  pod 'ReactiveObjC', '~> 3.1.0'
  
  pod 'XJHMultiProxyKit'
  
#  pod 'XJHMultiProxyKit', :path => '../../XJHMultiProxyKit', :inhibit_warnings => false

  target 'XJHTextInputIntercepterKit_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end
